import { YAMLServicesDefaultSetup, PROMConfig, JMXConfg, KafkaConnectCfg, KafkaBrokerCfg, ZooKeeperCfg, PrometheusConfig, GrafanaCfg, PGConfig, KSQLConfig, BaseCfg, KSQLSchemaCfg, Juypter, SparkCfg, SpringCfg, YAMLConfig } from '../types/yml';
export declare const downloadDir: string;
export declare const network = "localhost";
export declare const _ports_: YAMLServicesDefaultSetup;
export declare const PROMCONFIG: PROMConfig;
export declare const JMX: JMXConfg;
export declare const KAFKA_CONNECT_SRC: KafkaConnectCfg;
export declare const KAFKA_CONNECT_SINK: KafkaConnectCfg;
export declare const KAFKA_BROKER: KafkaBrokerCfg;
export declare const ZOOKEEPER: ZooKeeperCfg;
export declare const PROMETHEUS: PrometheusConfig;
export declare const GRAFANA: GrafanaCfg;
export declare const POSTGRES: PGConfig;
export declare const KSQL: KSQLConfig;
export declare const KSQL_CLI: BaseCfg;
export declare const KSQL_SCHEMA: KSQLSchemaCfg;
export declare const JUPYTER: Juypter;
export declare const SPARK: SparkCfg;
export declare const SPRING: SpringCfg;
export declare const YAML: YAMLConfig;
//# sourceMappingURL=yml.d.ts.map